# Generated by Django 2.1 on 2018-09-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Restaurant name', max_length=40)),
                ('info', models.TextField(help_text='Restaurant Info', max_length=500)),
                ('location', models.CharField(help_text='Restaurant location', max_length=40)),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='Joined date')),
                ('is_open', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=3)),
            ],
        ),
    ]
