# Generated by Django 2.1 on 2018-09-07 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular food across whole restaurant', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular sauce across whole restaurant', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Sauce name (e.g Chicken)', max_length=50)),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
