# Generated by Django 2.1 on 2018-09-07 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20180907_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular delivery area', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the delivery area (e.g Kamwokya)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular drink across whole restaurant', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='drink name (e.g Cocacola)', max_length=50)),
                ('category', models.CharField(choices=[('SD', 'Soft drink'), ('PJC', 'Packed Juice'), ('FJC', 'Fresh Juice'), ('ALC', 'Alcohol'), ('END', 'Energy drink')], max_length=4)),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
    ]
