# Generated by Django 2.1 on 2018-09-07 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_deliveryarea_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCombination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular food combination in the whole restaurant', primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('foods', models.ManyToManyField(help_text='Select a food to add on this food combination', to='restaurants.Food')),
                ('sauces', models.ManyToManyField(help_text='Select a sauce to add on this food combination', to='restaurants.Sauce')),
            ],
        ),
    ]
