# Generated by Django 2.1 on 2018-09-07 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_foodcombination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular dessert across the whole restaurant', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Dessert name (e.g Apple cake)', max_length=100)),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desserts', models.ManyToManyField(help_text='Select a dessert to add on the menu', to='restaurants.Dessert')),
                ('drinks', models.ManyToManyField(help_text='Select a drink to add on the menu', to='restaurants.Drink')),
                ('food_combinations', models.ManyToManyField(help_text='Select a food combination to add on the menu', to='restaurants.FoodCombination')),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular food across the whole restaurant', primary_key=True, serialize=False),
        ),
    ]
