# Generated by Django 2.1 on 2018-09-07 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20180907_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular restaurant', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the Restaurant (e.g Chop and chop restaurant)', max_length=100)),
                ('info', models.TextField(help_text='Say something about your restaurant', max_length=500)),
                ('location', models.CharField(help_text='Enter location of your restaurant (e.g Makerere Kikoni', max_length=50)),
                ('is_open', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=70)),
            ],
        ),
    ]
